# Generated by Django 3.2.10 on 2021-12-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('A_Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('A_tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('F_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StartTime', models.DateTimeField()),
                ('ArriveTime', models.DateTimeField()),
                ('Origin', models.CharField(max_length=20)),
                ('Destination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('TA_Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TA_Address', models.CharField(max_length=20)),
                ('TA_tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('U_Id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('U_Name', models.CharField(max_length=10)),
                ('U_Sex', models.CharField(max_length=2)),
                ('U_Company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('Destination', models.CharField(max_length=20)),
                ('U_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketSystem.userinfo')),
            ],
        ),
    ]
