# Generated by Django 3.2.10 on 2021-12-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightinfo',
            name='Price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
