# Generated by Django 3.2.10 on 2021-12-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0002_flightinfo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='U_Sex',
        ),
    ]
