# Generated by Django 3.2.10 on 2021-12-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0005_remove_userinfo_u_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelAgency',
        ),
    ]
