# Generated by Django 3.2.10 on 2021-12-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0007_delete_bookinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightinfo',
            name='A_Name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TicketSystem.airlines'),
        ),
    ]
