# Generated by Django 3.2.10 on 2021-12-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0008_flightinfo_a_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='0')),
                ('F_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketSystem.flightinfo')),
                ('U_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketSystem.userinfo')),
            ],
        ),
    ]
