# Generated by Django 3.2.10 on 2021-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0011_auto_20211223_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='O_Id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
