# Generated by Django 3.2.10 on 2021-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0014_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seat',
            field=models.IntegerField(default=0),
        ),
    ]
